version: "3.8"

services:
  react-app:
    container_name: esme_my_react_app
    build:
      context: .
      target: dev
    image: esme_my_react_app
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev -- --host
